# Generated by Django 6.0.4 on 2026-04-13 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.TextField()),
                ("platform", models.TextField()),
                ("status", models.TextField(default="processing")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sessions",
            },
        ),
        migrations.CreateModel(
            name="TwitterAuthor",
            fields=[
                (
                    "twitter_user_id",
                    models.TextField(primary_key=True, serialize=False),
                ),
                ("screen_name", models.TextField(blank=True, null=True)),
                ("display_name", models.TextField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("location", models.TextField(blank=True, null=True)),
                ("is_blue_verified", models.BooleanField(null=True)),
                ("followers_count", models.IntegerField(null=True)),
                ("following_count", models.IntegerField(null=True)),
                ("total_tweets", models.IntegerField(null=True)),
                ("account_created_at", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "twitter_authors",
            },
        ),
        migrations.CreateModel(
            name="TwitterPost",
            fields=[
                ("tweet_id", models.TextField(primary_key=True, serialize=False)),
                ("item_id", models.TextField(blank=True, null=True)),
                ("nav_index", models.TextField(blank=True, null=True)),
                ("source_platform_url", models.TextField(blank=True, null=True)),
                ("timestamp_collected", models.BigIntegerField(null=True)),
                ("conversation_id", models.TextField(blank=True, null=True)),
                ("is_reply", models.BooleanField(default=False)),
                ("in_reply_to_tweet_id", models.TextField(blank=True, null=True)),
                ("in_reply_to_screen_name", models.TextField(blank=True, null=True)),
                ("full_text", models.TextField(blank=True, null=True)),
                ("lang", models.TextField(blank=True, null=True)),
                ("tweet_created_at", models.TextField(blank=True, null=True)),
                ("is_quote_status", models.BooleanField(null=True)),
                ("possibly_sensitive", models.BooleanField(null=True)),
                ("promoted", models.BooleanField(default=False)),
                ("favorite_count", models.IntegerField(null=True)),
                ("retweet_count", models.IntegerField(null=True)),
                ("reply_count", models.IntegerField(null=True)),
                ("quote_count", models.IntegerField(null=True)),
                ("bookmark_count", models.IntegerField(null=True)),
                ("view_count", models.IntegerField(null=True)),
                ("hashtags", models.JSONField(blank=True, null=True)),
                ("mentioned_users", models.JSONField(blank=True, null=True)),
                ("raw_data", models.JSONField()),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.twitterauthor",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.session",
                    ),
                ),
            ],
            options={
                "db_table": "twitter_posts",
            },
        ),
    ]
