# Generated by Django 6.0.4 on 2026-05-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_llmanalysisrun"),
    ]

    operations = [
        migrations.AlterField(
            model_name="browsesession",
            name="status",
            field=models.TextField(
                choices=[
                    ("queued", "Queued"),
                    ("analyzing", "Analyzing"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                ],
                default="queued",
            ),
        ),
    ]
