from django.db import models

class Session(models.Model):
    # generated by your app, no ndjson equivalent
    user_id = models.TextField()
    # source_platform from ndjson outer envelope e.g. "twitter.com"
    platform = models.TextField()
    # managed by your app, tracks upload progress
    status = models.TextField(default='processing')
    # generated by your app
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'sessions'


class TwitterAuthor(models.Model):
    # data.core.user_results.result.rest_id
    twitter_user_id = models.TextField(primary_key=True)
    # data.core.user_results.result.core.screen_name
    screen_name = models.TextField(null=True, blank=True)
    # data.core.user_results.result.core.name
    display_name = models.TextField(null=True, blank=True)
    # data.core.user_results.result.legacy.description
    bio = models.TextField(null=True, blank=True)
    # data.core.user_results.result.location.location
    location = models.TextField(null=True, blank=True)
    # data.core.user_results.result.is_blue_verified
    is_blue_verified = models.BooleanField(null=True)
    # data.core.user_results.result.legacy.followers_count
    followers_count = models.IntegerField(null=True)
    # data.core.user_results.result.legacy.friends_count
    following_count = models.IntegerField(null=True)
    # data.core.user_results.result.legacy.statuses_count
    total_tweets = models.IntegerField(null=True)
    # data.core.user_results.result.core.created_at
    account_created_at = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'twitter_authors'


class TwitterPost(models.Model):
    # data.legacy.id_str
    tweet_id = models.TextField(primary_key=True)
    # foreign key to session
    session = models.ForeignKey(Session, on_delete=models.CASCADE, null=True)
    # foreign key to author
    author = models.ForeignKey(TwitterAuthor, on_delete=models.SET_NULL, null=True)
    # item_id outer envelope
    item_id = models.TextField(null=True, blank=True)
    # nav_index outer envelope
    nav_index = models.TextField(null=True, blank=True)
    # source_platform_url outer envelope
    source_platform_url = models.TextField(null=True, blank=True)
    # timestamp_collected outer envelope
    timestamp_collected = models.BigIntegerField(null=True)
    # data.legacy.conversation_id_str
    conversation_id = models.TextField(null=True, blank=True)
    # derived: true if in_reply_to_status_id_str exists
    is_reply = models.BooleanField(default=False)
    # data.legacy.in_reply_to_status_id_str
    in_reply_to_tweet_id = models.TextField(null=True, blank=True)
    # data.legacy.in_reply_to_screen_name
    in_reply_to_screen_name = models.TextField(null=True, blank=True)
    # data.legacy.full_text
    full_text = models.TextField(null=True, blank=True)
    # data.legacy.lang
    lang = models.TextField(null=True, blank=True)
    # data.legacy.created_at
    tweet_created_at = models.TextField(null=True, blank=True)
    # data.legacy.is_quote_status
    is_quote_status = models.BooleanField(null=True)
    # data.legacy.possibly_sensitive
    possibly_sensitive = models.BooleanField(null=True)
    # data.promoted
    promoted = models.BooleanField(default=False)
    # data.legacy.favorite_count
    favorite_count = models.IntegerField(null=True)
    # data.legacy.retweet_count
    retweet_count = models.IntegerField(null=True)
    # data.legacy.reply_count
    reply_count = models.IntegerField(null=True)
    # data.legacy.quote_count
    quote_count = models.IntegerField(null=True)
    # data.legacy.bookmark_count
    bookmark_count = models.IntegerField(null=True)
    # data.views.count
    view_count = models.IntegerField(null=True)
    # data.legacy.entities.hashtags[].text
    hashtags = models.JSONField(null=True, blank=True)
    # data.legacy.entities.user_mentions[].screen_name
    mentioned_users = models.JSONField(null=True, blank=True)
    # entire ndjson record stored as backup
    raw_data = models.JSONField()

    class Meta:
        db_table = 'twitter_posts'