from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from api.services.ingestion import ingest_posts

# csrf_exempt is a decorator that wraps the function and disables CSRF protection
# Request is the incoming HTTP request from the extension containing all the data — headers, body, method etc.


# CSRF stands for Cross-Site Request Forgery. It's a type of attack where a malicious website tricks your browser into making a request to another site you're logged into.
# Django protects against this by requiring every POST request to include a special secret token that only legitimate pages generated by Django would know.
# But our extension is not a Django-generated page. It's a browser extension running completely separately. It has no way to get that CSRF token from Django first.
# @csrf_exempt tells Django "skip the CSRF check for this specific endpoint."


@csrf_exempt
def import_dataset(request):
    platform = request.headers.get("X-Zeeschuimer-Platform", "unknown")
    user_agent = request.headers.get("User-Agent", None)
    body = request.body.decode("utf-8")

    try:
        session, post_count = ingest_posts(body, platform, user_agent)
    except ValueError as e:
        return JsonResponse({"error": str(e)}, status=400)

    return JsonResponse(
        {
            "status": "success",
            "session_id": str(session.id),
            "posts_received": post_count,
        }
    )
