from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from api.services.ingestion import ingest_posts

# csrf_exempt is a decorator that wraps the function and disables CSRF protection
# Request is the incoming HTTP request from the extension containing all the data — headers, body, method etc.


# CSRF stands for Cross-Site Request Forgery. It's a type of attack where a malicious website tricks your browser into making a request to another site you're logged into.
# Django protects against this by requiring every POST request to include a special secret token that only legitimate pages generated by Django would know.
# But our extension is not a Django-generated page. It's a browser extension running completely separately. It has no way to get that CSRF token from Django first.
# @csrf_exempt tells Django "skip the CSRF check for this specific endpoint."


@csrf_exempt
def import_dataset(request):
    platform = request.headers.get("X-Zeeschuimer-Platform", "unknown")
    user_agent = request.headers.get("User-Agent", None)
    body = request.body.decode("utf-8")

    try:
        session, post_count = ingest_posts(body, platform, user_agent)
    except ValueError as e:
        return JsonResponse({"error": str(e)}, status=400)

    return JsonResponse(
        {
            "status": "success",
            "session_id": str(session.id),
            "posts_received": post_count,
        }
    )


# ----------------------------------------------------------------------
# ADMIN/BACKGROUND views
# ----------------------------------------------------------------------


# PLACEHOLDER home/example endpoint usage (home.html doesn't exist yet)
def home(request):
    return render(request, "home.html", {})


# PLACEHOLDER login view
def login(request):
    return render(request, "login.html", {})


# PLACEHOLDER user profile view
def profile(request, user_id):
    user = AppUser.objects.filter(id=user_id)

    context = {
        "user": AppUser.objects.filter(id=user),
    }

    return render(request, "profile.html", context)


# PLACEHOLDER privacy agreement view
def privacy(request):
    return render(request, "privacy.html", {})


# PLACEHOLDER tutorial view
def tutorial(request):
    return render(request, "tutorial.html", {})


# ----------------------------------------------------------------------
# ANALYTICAL views
# ----------------------------------------------------------------------


# comprehensive view for all user-related feed analysis
def full_analysis(request, user_id):
    user = AppUser.objects.filter(id=user_id)
    # user_viewed_tweets = ViewedTweet.objects.filter(user=user).values_list("tweet", flat=True)

    context = {
        "user": AppUser.objects.filter(id=user),
        "sentiment_results": SentimentResult.objects.filter(
            tweet__viewedtweet__user=user
        ),
        "topic_results": TopicResult.objects.filter(tweet__viewedtweet__user=user),
        "political_leaning_results": PoliticalLeaningResult.objects.filter(
            tweet__viewedtweet__user=user
        ),
        "toxicity_results": ToxicityResult.objects.filter(
            tweet__viewedtweet__user=user
        ),
    }
    return render(request, "full_analysis.html", context)


# (PLACEHOLDER - html DOESNT EXIST YET)
def sentiment_results(request, user_id):
    user = AppUser.objects.filter(id=user_id)

    context = {
        "user": AppUser.objects.filter(id=user),
        "sentiment_results": SentimentResult.objects.filter(
            tweet__viewedtweet__user=user
        ),
    }
    return render(request, "sentiment.html", context)


# (PLACEHOLDER - html DOESNT EXIST YET)
def topic_results(request, user_id):
    user = AppUser.objects.filter(id=user_id)

    context = {
        "user": AppUser.objects.filter(id=user),
        "topic_results": TopicResult.objects.filter(tweet__viewedtweet__user=user),
    }
    return render(request, "topics.html", context)


# (PLACEHOLDER - html DOESNT EXIST YET)
def political_leaning_results(request, user_id):
    user = AppUser.objects.filter(id=user_id)

    context = {
        "user": AppUser.objects.filter(id=user),
        "political_leaning_results": PoliticalLeaningResult.objects.filter(
            tweet__viewedtweet__user=user
        ),
    }
    return render(request, "political_leaning.html", context)


# (PLACEHOLDER - html DOESNT EXIST YET)
def toxicity_results(request, user_id):
    user = AppUser.objects.filter(id=user_id)

    context = {
        "user": AppUser.objects.filter(id=user),
        "toxicity_results": ToxicityResult.objects.filter(
            tweet__viewedtweet__user=user
        ),
    }
    return render(request, "toxicity.html", context)
