import re

from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from api.services.ingestion import ingest_posts
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from .models import (
    AnalysisStatus,
    AppUser,
    BrowseSession,
    SentimentResult,
    TopicResult,
    ToxicityResult,
    Tweet,
    ViewedTweet,
)

# csrf_exempt is a decorator that wraps the function and disables CSRF protection
# Request is the incoming HTTP request from the extension containing all the data — headers, body, method etc.


# CSRF stands for Cross-Site Request Forgery. It's a type of attack where a malicious website tricks your browser into making a request to another site you're logged into.
# Django protects against this by requiring every POST request to include a special secret token that only legitimate pages generated by Django would know.
# But our extension is not a Django-generated page. It's a browser extension running completely separately. It has no way to get that CSRF token from Django first.
# @csrf_exempt tells Django "skip the CSRF check for this specific endpoint."


@csrf_exempt
def import_dataset(request):
    if not request.user.is_authenticated:
        return JsonResponse({"error": "not authenticated"}, status=401)

    platform = request.headers.get("X-Zeeschuimer-Platform", "unknown")
    user_agent = request.headers.get("User-Agent", None)
    body = request.body.decode("utf-8")

    try:
        session, post_count = ingest_posts(body, platform, user_agent, request.user)
    except ValueError as e:
        return JsonResponse({"error": str(e)}, status=400)
    except Exception as e:
        print(f"Ingestion failed: {e}")
        return JsonResponse({"error": "ingestion failed"}, status=500)

    return JsonResponse(
        {
            "status": "success",
            "session_id": str(session.id),
            "posts_received": post_count,
        }
    )


@csrf_exempt
def session_status(request, session_id):
    if not request.user.is_authenticated:
        return JsonResponse({"error": "not authenticated"}, status=401)

    try:
        session = BrowseSession.objects.get(id=session_id, user=request.user)
    except BrowseSession.DoesNotExist:
        return JsonResponse({"error": "session not found"}, status=404)

    tweet_ids = (
        ViewedTweet.objects.filter(session=session)
        .values_list("tweet_id", flat=True)
        .distinct()
    )
    tweet_count = tweet_ids.count()
    status_counts = {
        item["analysis_status"]: item["count"]
        for item in Tweet.objects.filter(tweet_id__in=tweet_ids)
        .values("analysis_status")
        .annotate(count=Count("tweet_id", distinct=True))
    }

    pending_count = status_counts.get(AnalysisStatus.PENDING, 0)
    processing_count = status_counts.get(AnalysisStatus.PROCESSING, 0)
    complete_count = status_counts.get(AnalysisStatus.COMPLETE, 0)
    failed_count = status_counts.get(AnalysisStatus.FAILED, 0)
    analyzed_count = complete_count + failed_count
    progress = round((analyzed_count / tweet_count) * 100) if tweet_count else 0

    return JsonResponse(
        {
            "session_id": str(session.id),
            "status": session.status,
            "tweet_count": tweet_count,
            "pending_count": pending_count,
            "processing_count": processing_count,
            "complete_count": complete_count,
            "failed_count": failed_count,
            "progress": progress,
        }
    )


# ----------------------------------------------------------------------
# ADMIN/BACKGROUND views
# ----------------------------------------------------------------------


@login_required
def home(request):
    return render(request, "home.html")


def signup(request):
    if request.method == "POST":
        form = AppUserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("login")

    else:
        form = AppUserCreationForm()

    return render(request, "registration/signup.html", {"form": form})


def onboarding(request):
    return render(request, "onboarding.html", {})


# PLACEHOLDER user profile view
def profile(request, user_id):
    user = AppUser.objects.filter(id=user_id)

    context = {
        "user": AppUser.objects.filter(id=user),
    }

    return render(request, "profile.html", context)


# PLACEHOLDER privacy agreement view
def privacy(request):
    return render(request, "privacy.html", {})


# ----------------------------------------------------------------------
# ANALYTICAL views
# ----------------------------------------------------------------------


TOPIC_SERIES_NAME = "Topic as a Percent of Tweets"


def topics_page(request):
    return render(request, "topics.html")


def _format_topic_label(topic):
    if not topic:
        return ""

    cleaned = re.sub(r"[_-]+", " ", topic).strip()
    small_words = {"and", "or", "of", "the", "a", "an", "to", "in", "for", "on", "with"}
    words = cleaned.split()
    formatted = []
    for index, word in enumerate(words):
        lower = word.lower()
        if index != 0 and lower in small_words:
            formatted.append(lower)
        else:
            formatted.append(lower[:1].upper() + lower[1:])
    return " ".join(formatted)


def _get_topic_summary(user):
    tweet_ids = ViewedTweet.objects.filter(user=user).values_list("tweet_id", flat=True)

    topic_counts = (
        TopicResult.objects.filter(tweet_id__in=tweet_ids)
        .values("topic")
        .annotate(count=Count("topic"))
        .order_by("-count", "topic")[:5]
    )
    total = TopicResult.objects.filter(tweet_id__in=tweet_ids).count()

    categories = [_format_topic_label(item["topic"]) for item in topic_counts]
    data = (
        [round((item["count"] / total) * 100) for item in topic_counts] if total else []
    )

    return categories, data


# comprehensive view for all user-related feed analysis
def full_analysis(request, user_id):
    user = AppUser.objects.filter(id=user_id)
    # user_viewed_tweets = ViewedTweet.objects.filter(user=user).values_list("tweet", flat=True)

    context = {
        "user": AppUser.objects.filter(id=user),
        "sentiment_results": SentimentResult.objects.filter(
            tweet__viewedtweet__user=user
        ),
        "topic_results": TopicResult.objects.filter(tweet__viewedtweet__user=user),
        "toxicity_results": ToxicityResult.objects.filter(
            tweet__viewedtweet__user=user
        ),
    }
    return render(request, "full_analysis.html", context)


def topic_results(request, user_id=None):
    if user_id is None:
        user_id = request.session.get("user_id")

    try:
        user = AppUser.objects.get(id=user_id)
    except AppUser.DoesNotExist:
        return JsonResponse({"error": "user not found"}, status=404)

    context = {
        "user": user,
        "topic_results": TopicResult.objects.filter(tweet__viewedtweet__user=user),
    }
    return render(request, "topic_results.html", context)


def topic_distribution(request):
    """
    GET /api/topics

    Returns the top 5 topics for a user's feed as percentages.
    Used to render the animated bar graph on the feed analysis page.
    """
    user_id = request.session.get("user_id")
    if not user_id:
        return JsonResponse({"error": "not authenticated"}, status=401)

    try:
        user = AppUser.objects.get(id=user_id)
    except AppUser.DoesNotExist:
        return JsonResponse({"error": "user not found"}, status=404)

    categories, data = _get_topic_summary(user)

    return JsonResponse(
        {
            "categories": categories,
            "data": data,
        }
    )


def topic_summary(request):
    """
    GET /api/topics-summary/

    Returns the top 5 topics for the current user in the chart format used by
    the frontend dashboard.
    """
    if not request.user.is_authenticated:
        return JsonResponse({"error": "not authenticated"}, status=401)

    categories, data = _get_topic_summary(request.user)

    return JsonResponse(
        {
            "categories": categories,
            "series": [
                {
                    "name": TOPIC_SERIES_NAME,
                    "data": data,
                }
            ],
        }
    )
